// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Lovable export sometimes uses VITE_SUPABASE_PUBLISHABLE_KEY, while many setups use VITE_SUPABASE_ANON_KEY.
// Support both to avoid deploy issues (e.g., Vercel env var mismatch).
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
export const SUPABASE_KEY =
  // Prefer ANON key first. Some deployments accidentally set PUBLISHABLE_KEY to an access token,
  // which breaks requests (e.g. apikey header becomes a JWT). Keep PUBLISHABLE only as fallback.
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Guardrail: if someone accidentally puts an access token in the key env var, surface it loudly.
if (typeof SUPABASE_KEY === "string" && SUPABASE_KEY.startsWith("eyJ")) {
  // eslint-disable-next-line no-console
  console.error(
    "Supabase key env var looks like a JWT. Use the project's ANON key in VITE_SUPABASE_ANON_KEY.",
  );
}

if (!SUPABASE_URL || !SUPABASE_KEY) {
  // Fail fast with a helpful message instead of confusing 401/404 errors.
  // eslint-disable-next-line no-console
  console.error(
    "Supabase env vars missing. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY).",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: "sb-dashboard-mrl",
    storage: localStorage,
  }
});